version: '3'
services:
  moleclue:
    container_name: moleclue
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/workspace"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true